### PR TITLE
RFC: revert removal of support for manual node ID

### PR DESCRIPTION
**Pull request by rubo77**
(reverted from commit 66bd85ea86571b59b324b4393ddbb34916e2c891)

untested, but we should re-enable this. Maybe we should add a config option to show the mac-address input filed or not?

### CODE REVIEW

**Comment by RalfJung** [comment]
It's not the MAC address, it's the node ID. Gluon happens to usually compute that from one of the many MAC addresses of the device, but I don't think mixing up terminology here is a good idea.

Also, if possible I'd like to avoid having two input boxes.  Can you instead turn the drop-down into a freely editable field with auto-completion?

**Comment by RalfJung** [comment]
Closing due to inactivity. If you find a good way to make this into a single input element, feel free to reopen!

**Comment by rubo77** [comment]
please reopen, I plan to do this, when I find the time, (seems not so complicated)

**Comment by RalfJung** [comment]
Sure, I'll reopen when there is something to review. :)  I'd like to keep the pull requests limited to something actionable.

**Comment by rubo77** [comment]
Maybe we can leave this open and a tag "planned for later' or so.

Otherwise good ideas get lost in the list of closed issues

**Comment by RalfJung** [comment]
This is not an issue though, it is a PR.

If you want to file an issue, that's okay for me.

**Pull request closed without merging**
