### PR TITLE
Readme: add port to cron curl command

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by RalfJung** [comment]
That's not correct. `$ROOT_URL` is supposed to already be the URL under which the service is available, and it is used e.g. in the confirmation emails. If the port is really needed, it should be in the `$ROOT_URL` (i.e., in the `root_url` setting).

**Comment by rubo77** [comment]
Then there should be such a note in the readme

**Comment by RalfJung** [comment]
A note saying what? That "replacing $ROOT_URL by your root URL" refers to the `root_url` setting?

**Comment by rubo77** [comment]
That the port must be in the root URL include (If served with port)

**Comment by RalfJung** [comment]
What do you mean by "served with port"?

With the usual setup (as described in the README), the service listens on port 8833 but there is a n nginx/... running on port 80 that acts as reverse proxy. In that case, there should be no port in either the `root` setting or the cronjob URL. I am not sure what your setup is, but clearly the documentation cannot account for sysadmins making their own choices and diverging from the recommended setup.

**Comment by RalfJung** [comment]
I slightly edited README and Rocket.toml.dist to hopefully clarify how the URLs usually look.

**Comment by rubo77** [comment]
Should be

    root = "https://host:port/node-monitor"

**Comment by rubo77** [comment]
I am not working today. Feel free to pick any of my suggestions and enhance it

**Comment by RalfJung** [comment]
> `root = "https://host:port/node-monitor"`

No. There's no port most of the times, e.g. if people follow the instructions and set up an nginx.

**Comment by rubo77** [comment]
Then maybe the hint

> Add the port to the URL, if needed

**Comment by RalfJung** [comment]
But that's how URLs work everywhere, all the time, isn't it?

**Comment by rubo77** [comment]
For uns it is clear, but for non-admins that hint would be clear

**Comment by RalfJung** [comment]
I have a hard time imagining someone setting up this software in a non-default way (!) and not knowing about ports in URLs.

**Pull request closed without merging**
