### PR TITLE
Enhance style and entry page

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks! This already looks much better. :)

One question: Can you make it so that the drop-down for selecting the node and the button stay in the same row? Currently they are next to each other, with your patch they occupy two lines:

**Comment by rubo77** [comment]
That depends on the longest node name.
But you could give the select a max-width

**Comment by RalfJung** [comment]
Well I'm not very knowledgeable in modern CSS, but can you say "make it take all the space except for what is needed for the button"?

**Comment by rubo77** [comment]
Try this out.

With F12 you can change the width to the optimum in Firefox. 

See u tomorrow 😊

**Comment by RalfJung** [comment]
I guess that'll do it, thanks!

**Pull request merged**
